version: "3"
services:
  ServerNode:
    build: ./services/ServerNode
    ports:
      - "5001:5001"
    depends_on:
      - db
    container_name: crud-serverNODE
  client_react_ts:
    build: ./services/client_react_ts
    ports:
      - "3000:3000"
    container_name: crud-client
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: crud-db
